"use strict";
var Guestlist = ["Maryam", "Mehak", "Zahra", "kalsoom"];
console.log("I would be really happy if you " + Guestlist[0] + "   come to my birthday party");
console.log("I would be really happy if you " + Guestlist[1] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[2] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[3] + "  come to my birthday party");
console.log(Guestlist[1] + "cannot come due to some urgent piece of work ");
Guestlist[1] = "Yusra";
console.log("I would be really happy if you " + Guestlist[0] + " come to my birthday party");
console.log("I would be really happy if you " + Guestlist[1] + " come to my birthday party");
console.log("I would be really happy if you " + Guestlist[2] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[3] + "  come to my birthday party");
console.log("I found a bigger dinner table for my birthday dinner .I am so much excited ");
Guestlist.unshift("Areeba");
Guestlist.splice(2, 0, "Nida");
console.log("I would be really happy if you " + Guestlist[0] + "   come to my birthday party");
console.log("I would be really happy if you " + Guestlist[1] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[2] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[3] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[4] + "  come to my birthday party");
console.log(Guestlist);
