"use strict";
var Guestlist = ["Maryam", "Mehak", "Zahra", "kalsoom"];
console.log("I would be really happy if you " + Guestlist[0] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[1] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[2] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[3] + "  come to my birthday party");
console.log(Guestlist[1] + "cannot come due to some urgent piece of work ");
Guestlist[1] = "Yusra";
console.log("I would be really happy if you " + Guestlist[0] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[1] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[2] + "  come to my birthday party");
console.log("I would be really happy if you " + Guestlist[3] + "  come to my birthday party");
